### ISSUE TITLE
Release 2.2.4 with fixes from #93 ?

### ISSUE THREAD

**Issue by henrik242** [constretto/constretto-core#116]
We use Constretto a lot in my company. Is there a chance of releasing a 2.2.4 with just the fixes from #93?  Right now we're using a custom-built version of Constretto just for this.

**Comment by henrik242** [comment]
Ping @zapodot

**Comment by zapodot** [comment]
Hi! What is stopping you from using the latest release?

There should not be to many changes from the latest 2.x release

**Comment by henrik242** [comment]
@zapodot It'll check it out. But it'd be nice if some dependencies were updated in it, there are multiple vulnerabilities from them: https://mvnrepository.com/artifact/org.constretto/constretto-core/3.0.0-BETA1

**Comment by henrik242** [comment]
3.0.0-BETA1 works!

**Comment by henrik242** [comment]
@zapodot Are you sure these changes are in 3.0.0-BETA1? I just unpacked constretto-api-3.0.0-BETA1-sources.jar and they weren't there.
