### ISSUE TITLE
Update dependencies with vulnerabilities in 3.0.0-BETA1

### ISSUE THREAD

**Issue by henrik242** [constretto/constretto-core#123]
There are multiple vulnerabilities in dependencies of 3.0.0-BETA1 (junit, commons-beanutils, snakeyaml & gson).

See: https://mvnrepository.com/artifact/org.constretto/constretto-core/3.0.0-BETA1

(First mentioned in https://github.com/constretto/constretto-core/issues/116#issuecomment-1166578702 )

**Comment by henrik242** [comment]
Most (all?) of these have PRs by dependabot already. Any chance you could merge & release, @zapodot ?

**Comment by zapodot** [comment]
Merged all dependabot PR-s and released. Please update to v. 3.0.0-BETA4 to get the latest changes
