### ISSUE TITLE
Memory leak in DefaultConstrettoConfiguration

### ISSUE THREAD

**Issue by kaaveland** [constretto/constretto-core#57]
Hi,

We encountered a memory leak in a long-running process using constretto. We tracked it down to `DefaultConstrettoConfiguration.configuredObjects`, which is a `CopyOnWriteArraySet<WeakReference<Object>>`. The `WeakReference` instances themselves are not collected and the backing array of the `CopyOnWriteArraySet` is never cleared. What ended up happening is that we had multiple copies of an array of `WeakReference<Object>` where the references were mostly pointing to `null`. Probably this is only a problem for us because we need configure a lot of request-scoped classes.

There should probably be some sort of logic for removing things from the `Set<WeakReference<Object>>`, but it might require the use of a different data-structure seeing as operations that mutate `CopyOnWriteArraySet` require copying the underlying array. The methods that use the values in `configuredObjects` are deprecated, so removing the code might also be an option.

**Comment by zapodot** [comment]
The code in question will as you say be removed in the next release as a result of fixing #35.

Anyway: thx for reporting back to us
