### ISSUE TITLE
Will Constretto 3.0 be released?

### ISSUE THREAD

**Issue by MarthaAlfsvaag** [constretto/constretto-core#67]
Issue #51, #52 (support of spring 4.1.x)  is closed in the 3.0 branch. Will there be an release of this branch anytime soon?

**Comment by zapodot** [comment]
@MarthaAlfsvaag at some point it will. I do hope to be able to get it done in the next months, possibly by adjusting the scope of the release somewhat. Stay put!

**Comment by baardl** [comment]
Hi @zapodot 
The issue with missing support for Spring > 3.2.x and java > 1.7 is getting urgent.
Are there any possibility for branching out your fix for those issues?

**Comment by hamnis** [comment]
A suggestion could be to move the remaining features to 4.0 and release what we have ( assuming that is feature complete) @kaarenilsen @zapodot

**Comment by zapodot** [comment]
@hamnis probably a good idea. A 3.0 release of the current changes should not be too much work. @baardl: note that starting with 3.0, the Spring integration is moved to from Constretto Core to its own separate repository (https://github.com/constretto/constretto-spring) which will make it easier to follow Spring release cycles in the future.

**Comment by baardl** [comment]
Sounds very well. :)

Also Java 9 is coming at full speed. Guess that will impact a 4.0 release
:-)

Thanks.

**Comment by zapodot** [comment]
@baardl just released the first beta of Constretto Spring 3 containing support for Spring v.4.X. Details: https://github.com/constretto/constretto-spring/releases/tag/r.3.0.0-beta1

**Comment by baardl** [comment]
Thank you.
Will check it out early next week.

B.

Den fre. 9. mar. 2018, 16.39 skrev Sondre Eikanger Kvalø <
notifications@github.com>:

**Comment by henrik242** [comment]
👀
