### ISSUE TITLE
Constretto official website is down?

### ISSUE THREAD

**Issue by mythnc** [constretto/constretto-core#89]
I can't access [Constretto official website](http://constretto.github.io) currently.

It redirects to me to here:

![截圖 2021-05-28 13 51 32](https://user-images.githubusercontent.com/459105/119931177-d8adf200-bfbb-11eb-8b1c-49ffe55bed79.png)

**Comment by henrik242** [comment]
Maybe links to that site should be taken away @zapodot ?

**Comment by kaarenilsen** [comment]
Yeah.. Have stopped paying for that domain :)

**Comment by zapodot** [comment]
I changed the links on the project page a long time ago so closing this for now

**Comment by mythnc** [comment]
Could you show me the latest links? Thank you.

Either http://constretto.org or http://constretto.github.io is not official site.


<img width="935" alt="link1" src="https://user-images.githubusercontent.com/459105/175823861-c04d5295-6c86-4f0d-b147-59956989430e.png">

<img width="393" alt="link2" src="https://user-images.githubusercontent.com/459105/175823864-8ef209bf-07c5-42a6-bfe3-b8ef6fb2b038.png">

**Comment by henrik242** [comment]
Also in the pom: https://github.com/constretto/constretto-core/blob/859314ed749b750a04ac859624ff78810f4e6009/pom.xml#L18
